version: "2.1"

services:

  TRAEFIK:
    image: "traefik:v2.9"
    container_name: "TRAEFIK"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accessLog=/var/log/traefik/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - --entrypoints.web.forwardedHeaders.insecure=true
      - --entrypoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32
      #- --entrypoints.web.ProxyProtocol.insecure=true
      - --entrypoints.web.ProxyProtocol.trustedIPs=127.0.0.1/32
    # labels:
      # - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      # - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - DOMAIN
    volumes:
      - ./logs/traefik:/var/log/traefik
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"
      
  # whoami2:
  #   image: "traefik/whoami"
  #   container_name: "simple-service2"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami2.rule=Host(`whoami.${DOMAIN}`) && PathPrefix(`/h2`)"
  #     - "traefik.http.routers.whoami2.entrypoints=web"
  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    environment:
      - DOMAIN
      - CDN
    links:
      #  - XRAYR:XRAYR
       - SSPANEL:SSPANEL
       - TRAEFIK:TRAEFIK
    # depends_on:
    #   - XRAYR
    ports:
      - 443:443
    expose:
      - 443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./etc/nginx/templates/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    environment:
      - DOMAIN
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  SSPANEL:
    image: ttracy/panel
    container_name: SSPANEL
    restart: always
    expose: 
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.sspanel.rule: Host(`${DOMAIN}`)
      traefik.http.routers.sspanel.entrypoints: web
      # traefik.http.services.sspanel.loadbalancer.server.port: 8080
    volumes:
      - ./config/.config.php:/var/www/config/.config.php
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SSPANEL_KEY: ChangeMe
      SSPANEL_APP_NAME: SSPanel-UIM
      SSPANEL_BASEURL: https://${DOMAIN}
      SSPANEL_MUKEY: SSPANEL
      SSPANEL_ADMIN_EMAIL: admin@${DOMAIN}.com
      SSPANEL_ADMIN_PASSWORD: V3ryL0ngP@ssw0rd
      DEBUG: "false"
      TIME_ZONE: Asia/Tehran
      STREAMING_UNLOCK: "false"
      GITHUB_ACCESS_TOKEN:
      ENABLE_TELEGRAM: "false"
      TELEGRAM_TOKEN:
      TELEGRAM_CHAT_ID:
      TELEGRAM_BOT: EXAMPLE_bot
      TELEGRAM_LOGIN: "false"
      B2_BACKUP_NAME: SSPANEL
      B2_BACKUP: "false"
      B2_APP_KEY_ID:
      B2_APP_KEY:
      B2_BUCKET_NAME:
      B2_COMPRESS_METHOD: zip
      DB_HOST: ss_db
      DB_PORT: 3306
      DB_DATABASE: sspanel
      DB_PASSWORD: sspanel
      DB_USERNAME: root
  mariadb:
    image: mariadb:10.9
    container_name: ss_db
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: sspanel
      MYSQL_DATABASE: sspanel
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - PMA_ARBITRARY=1

  xray_vlessws:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_vlessws
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3005
    labels:
      traefik.enable: true
      traefik.http.routers.xray_vlessws.rule: Host(`${DOMAIN}`) && Path(`/vlessws`)
      traefik.http.routers.xray_vlessws.service: xray_vlessws
      traefik.http.routers.xray_vlessws.entrypoints: web
      traefik.http.services.xray_vlessws.loadbalancer.server.port: 3005
      
  xray_vmessws:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_vmessws
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3006
    labels:
      traefik.enable: true
      traefik.http.routers.xray_vmessws.rule: Host(`${DOMAIN}`) && Path(`/vmessws`)
      traefik.http.routers.xray_vmessws.service: xray_vmessws
      traefik.http.routers.xray_vmessws.entrypoints: web
      traefik.http.services.xray_vmessws.loadbalancer.server.port: 3006

  xray_trojanws:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_trojanws
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3007
    labels:
      traefik.enable: true
      traefik.http.routers.xray_trojanws.rule: Host(`${DOMAIN}`) && Path(`/trojanws`)
      traefik.http.routers.xray_trojanws.service: xray_trojanws
      traefik.http.routers.xray_trojanws.entrypoints: web
      traefik.http.services.xray_trojanws.loadbalancer.server.port: 3007

  xray_vltc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_vltc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3010
    labels:
      traefik.enable: true
      traefik.http.routers.xray_vltc.rule: Host(`${DOMAIN}`) && Path(`/vltc`)
      traefik.http.routers.xray_vltc.service: xray_vltc
      traefik.http.routers.xray_vltc.entrypoints: web
      traefik.http.services.xray_vltc.loadbalancer.server.port: 3010

  xray_vmtc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_vmtc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3011
    labels:
      traefik.enable: true
      traefik.http.routers.xray_vmtc.rule: Host(`${DOMAIN}`) && Path(`/vmtc`)
      traefik.http.routers.xray_vmtc.service: xray_vmtc
      traefik.http.routers.xray_vmtc.entrypoints: web
      traefik.http.services.xray_vmtc.loadbalancer.server.port: 3011

  xray_trtc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_trtc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3009
    labels:
      traefik.enable: true
      traefik.http.routers.xray_trtc.rule: Host(`${DOMAIN}`) && Path(`/trtc`)
      traefik.http.routers.xray_trtc.service: xray_trtc
      traefik.http.routers.xray_trtc.entrypoints: web
      traefik.http.services.xray_trtc.loadbalancer.server.port: 3009


  xray_h2:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_h2
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3008
    labels:
      traefik.enable: true
      traefik.http.routers.xray_h2.rule: Host(`${DOMAIN}`) && Path(`/h2`)
      traefik.http.routers.xray_h2.service: xray_h2
      traefik.http.routers.xray_h2.entrypoints: web
      traefik.http.services.xray_h2.loadbalancer.server.port: 3008

  xray_trgrpc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_trgrpc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3001
    labels:
      traefik.enable: true
      traefik.http.routers.xray_trgrpc.rule: Host(`${DOMAIN}`) && Path(`/trgrpc`)
      traefik.http.routers.xray_trgrpc.service: xray_trgrpc
      traefik.http.routers.xray_trgrpc.entrypoints: web
      traefik.http.services.xray_trgrpc.loadbalancer.server.port: 3001
      traefik.http.services.xray_trgrpc.loadbalancer.server.scheme: h2c

  xray_vlgrpc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_vlgrpc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3002
    labels:
      traefik.enable: true
      traefik.http.routers.xray_vlgrpc.rule: Host(`${DOMAIN}`) && Path(`/vlgrpc`)
      traefik.http.routers.xray_vlgrpc.service: xray_vlgrpc
      traefik.http.routers.xray_vlgrpc.entrypoints: web
      traefik.http.services.xray_vlgrpc.loadbalancer.server.port: 3002
      traefik.http.services.xray_vlgrpc.loadbalancer.server.scheme: h2c

  xray_vmgrpc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_vmgrpc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3002
    labels:
      traefik.enable: true
      traefik.http.routers.xray_vmgrpc.rule: Host(`${DOMAIN}`) && Path(`/vmgrpc`)
      traefik.http.routers.xray_vmgrpc.service: xray_vmgrpc
      traefik.http.routers.xray_vmgrpc.entrypoints: web
      traefik.http.services.xray_vmgrpc.loadbalancer.server.port: 3003
      traefik.http.services.xray_vmgrpc.loadbalancer.server.scheme: h2c

  xray_ssgrpc:
    image: ghcr.io/xrayr-project/xrayr:latest
    container_name: xray_ssgrpc
    restart: unless-stopped
    depends_on:
      - TRAEFIK
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./config:/etc/XrayR
      - ./log:/var/log/XrayR
    expose:
      - 3002
    labels:
      traefik.enable: true
      traefik.http.routers.xray_ssgrpc.rule: Host(`${DOMAIN}`) && Path(`/ssgrpc`)
      traefik.http.routers.xray_ssgrpc.service: xray_ssgrpc
      traefik.http.routers.xray_ssgrpc.entrypoints: web
      traefik.http.services.xray_ssgrpc.loadbalancer.server.port: 3004
      traefik.http.services.xray_ssgrpc.loadbalancer.server.scheme: h2c
